public class FindTheDifference {
/* You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
* */
    public char findTheDifferenceSolution(String s, String t) {
        int[] count = new int[26];

        for (int i=0; i<t.length(); i++) {
            count[t.charAt(i) - 'a']++;
        }
//        System.out.println(count);

        for (int i=0; i<s.length(); i++) {
            count[s.charAt(i) - 'a']--;
        }
//        System.out.println(count);

        for (int i=0; i<26; i++) {
            if(count[i]==1) {
                return (char) (i+'a');
            }
        }

        return ' ';
    }
}
